# CMake generated Testfile for 
# Source directory: /home/paddy/pkg/dune_2d/pdelab_interface/dune/pdelab/test
# Build directory: /home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testanalytic "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testanalytic")
set_tests_properties(testanalytic PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testanalytic" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testbindtime "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testbindtime")
set_tests_properties(testbindtime PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testbindtime" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testclock "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testclock")
set_tests_properties(testclock PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testclock" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testcomplexnumbers-istl "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testcomplexnumbers-istl")
set_tests_properties(testcomplexnumbers-istl PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testcomplexnumbers-istl" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testcomplexnumbers-istlbackend "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testcomplexnumbers-istlbackend")
set_tests_properties(testcomplexnumbers-istlbackend PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testcomplexnumbers-istlbackend" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testconstraints "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testconstraints")
set_tests_properties(testconstraints PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testconstraints" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testdunefunctionsgfs "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testdunefunctionsgfs")
set_tests_properties(testdunefunctionsgfs PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdunefunctionsgfs" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testelectrodynamic "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testelectrodynamic")
set_tests_properties(testelectrodynamic PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testelectrodynamic" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testfunction "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testfunction")
set_tests_properties(testfunction PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testfunction" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testgridfunctionspace "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testgridfunctionspace")
set_tests_properties(testgridfunctionspace PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testgridfunctionspace" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testgridfunctionspace-fixedsize "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testgridfunctionspace-fixedsize")
set_tests_properties(testgridfunctionspace-fixedsize PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testgridfunctionspace-fixedsize" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpowergridfunctionspace-fixedsize "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpowergridfunctionspace-fixedsize")
set_tests_properties(testpowergridfunctionspace-fixedsize PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpowergridfunctionspace-fixedsize" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testplasticitygfs "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testplasticitygfs")
set_tests_properties(testplasticitygfs PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testplasticitygfs" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testheat-instationary-periodic "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testheat-instationary-periodic")
set_tests_properties(testheat-instationary-periodic PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testheat-instationary-periodic" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testelasticity "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testelasticity")
set_tests_properties(testelasticity PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testelasticity" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testdglegendre "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testdglegendre")
set_tests_properties(testdglegendre PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdglegendre" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testfastdgassembler "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testfastdgassembler")
set_tests_properties(testfastdgassembler PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testfastdgassembler" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testinstationaryfastdgassembler "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testinstationaryfastdgassembler")
set_tests_properties(testinstationaryfastdgassembler PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testinstationaryfastdgassembler" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testlocalfunctionspace "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testlocalfunctionspace")
set_tests_properties(testlocalfunctionspace PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testlocalfunctionspace" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testlocaloperatorinterface "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testlocaloperatorinterface")
set_tests_properties(testlocaloperatorinterface PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testlocaloperatorinterface" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpk2dinterpolation "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpk2dinterpolation")
set_tests_properties(testpk2dinterpolation PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpk2dinterpolation" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpk "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpk")
set_tests_properties(testpk PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpk" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson")
set_tests_properties(testpoisson PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testchunkedblockordering "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testchunkedblockordering")
set_tests_properties(testchunkedblockordering PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testchunkedblockordering" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt0 "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testrt0")
set_tests_properties(testrt0 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt0" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt02dgridfunctionspace "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testrt02dgridfunctionspace")
set_tests_properties(testrt02dgridfunctionspace PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt02dgridfunctionspace" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testutilities "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testutilities")
set_tests_properties(testutilities PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testutilities" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testinterpolate "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testinterpolate")
set_tests_properties(testinterpolate PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testinterpolate" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-instationary-with-boundary-constraints "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/test-instationary-with-boundary-constraints")
set_tests_properties(test-instationary-with-boundary-constraints PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-instationary-with-boundary-constraints" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnumericaljacobianmethods "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnumericaljacobianmethods")
set_tests_properties(testnumericaljacobianmethods PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testnumericaljacobianmethods" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrtfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testrtfem")
set_tests_properties(testrtfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrtfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testbdmfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testbdmfem")
set_tests_properties(testbdmfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testbdmfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testvectoriterator "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testvectoriterator")
set_tests_properties(testvectoriterator PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testvectoriterator" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpermutedordering "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpermutedordering")
set_tests_properties(testpermutedordering PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpermutedordering" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testsimplebackend "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testsimplebackend")
set_tests_properties(testsimplebackend PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testsimplebackend" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-transport-ccfv "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/test-transport-ccfv")
set_tests_properties(test-transport-ccfv PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-transport-ccfv" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testeigenbackend "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testeigenbackend")
set_tests_properties(testeigenbackend PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testeigenbackend" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopbfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testopbfem")
set_tests_properties(testopbfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopbfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-dg-amg "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/test-dg-amg")
set_tests_properties(test-dg-amg PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-dg-amg" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg1-dg0-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg1-dg0-parallel")
set_tests_properties(testpoisson-periodic-2d-deg1-dg0-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-2d-deg1-dg0-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg1-dg0-parallel-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg1-dg0-parallel")
set_tests_properties(testpoisson-periodic-2d-deg1-dg0-parallel-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testpoisson-periodic-2d-deg1-dg0-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-3d-deg1-dg0-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-3d-deg1-dg0-parallel")
set_tests_properties(testpoisson-periodic-3d-deg1-dg0-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-3d-deg1-dg0-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg1-dg1-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg1-dg1-parallel")
set_tests_properties(testpoisson-periodic-2d-deg1-dg1-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-2d-deg1-dg1-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg1-dg1-parallel-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg1-dg1-parallel")
set_tests_properties(testpoisson-periodic-2d-deg1-dg1-parallel-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testpoisson-periodic-2d-deg1-dg1-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-3d-deg1-dg1-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-3d-deg1-dg1-parallel")
set_tests_properties(testpoisson-periodic-3d-deg1-dg1-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-3d-deg1-dg1-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg2-dg0-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg2-dg0-parallel")
set_tests_properties(testpoisson-periodic-2d-deg2-dg0-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-2d-deg2-dg0-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg2-dg0-parallel-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg2-dg0-parallel")
set_tests_properties(testpoisson-periodic-2d-deg2-dg0-parallel-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testpoisson-periodic-2d-deg2-dg0-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-3d-deg2-dg0-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-3d-deg2-dg0-parallel")
set_tests_properties(testpoisson-periodic-3d-deg2-dg0-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-3d-deg2-dg0-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg2-dg1-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg2-dg1-parallel")
set_tests_properties(testpoisson-periodic-2d-deg2-dg1-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-2d-deg2-dg1-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-2d-deg2-dg1-parallel-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-2d-deg2-dg1-parallel")
set_tests_properties(testpoisson-periodic-2d-deg2-dg1-parallel-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testpoisson-periodic-2d-deg2-dg1-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testpoisson-periodic-3d-deg2-dg1-parallel "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testpoisson-periodic-3d-deg2-dg1-parallel")
set_tests_properties(testpoisson-periodic-3d-deg2-dg1-parallel PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testpoisson-periodic-3d-deg2-dg1-parallel" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnonoverlappingsinglephaseflow-yasp "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnonoverlappingsinglephaseflow-yasp")
set_tests_properties(testnonoverlappingsinglephaseflow-yasp PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testnonoverlappingsinglephaseflow-yasp" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnonoverlappingsinglephaseflow-yasp-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnonoverlappingsinglephaseflow-yasp")
set_tests_properties(testnonoverlappingsinglephaseflow-yasp-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testnonoverlappingsinglephaseflow-yasp" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnonoverlappingsinglephaseflow-ug "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnonoverlappingsinglephaseflow-ug")
set_tests_properties(testnonoverlappingsinglephaseflow-ug PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testnonoverlappingsinglephaseflow-ug" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnonoverlappingsinglephaseflow-ug-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnonoverlappingsinglephaseflow-ug")
set_tests_properties(testnonoverlappingsinglephaseflow-ug-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testnonoverlappingsinglephaseflow-ug" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnonoverlappingsinglephaseflow-boilerplate-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnonoverlappingsinglephaseflow-boilerplate")
set_tests_properties(testnonoverlappingsinglephaseflow-boilerplate-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testnonoverlappingsinglephaseflow-boilerplate" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testadaptivity "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testadaptivity")
set_tests_properties(testadaptivity PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testadaptivity" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testnonoverlapping-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/testnonoverlapping")
set_tests_properties(testnonoverlapping-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "testnonoverlapping" SKIP_RETURN_CODE "77" TIMEOUT "300")
subdirs("fem")
