# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget dunepdelab)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target dunepdelab
add_library(dunepdelab STATIC IMPORTED)

set_target_properties(dunepdelab PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ENABLE_EIGEN=1;ENABLE_UG=1;ModelP;ENABLE_SUITESPARSE=1;ENABLE_SUPERLU=1;ENABLE_GMP=1;ENABLE_MPI=1;MPICH_SKIP_MPICXX;MPIPP_H;MPI_NO_CPPBIND"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/local/include/eigen3;/home/paddy/pkg/dune_2d/dune-functions;/home/paddy/pkg/dune_2d/dune-localfunctions;/home/paddy/pkg/dune_2d/dune-grid;/home/paddy/pkg/dune_2d/dune-typetree;/home/paddy/pkg/dune_2d/dune-istl;/usr/include/suitesparse;/usr/include/superlu;/home/paddy/pkg/dune_2d/dune-geometry;/home/paddy/pkg/dune_2d/dune-uggrid;/home/paddy/pkg/dune_2d/dune-common;/usr/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include"
  INTERFACE_LINK_LIBRARIES "dunegrid;dunegeometry;ugS3;ugS2;ugL;dunecommon;dunegrid;dunegeometry;ugS3;ugS2;ugL;dunecommon;/usr/lib/x86_64-linux-gnu/libldl.so;/usr/lib/x86_64-linux-gnu/libspqr.so;/usr/lib/x86_64-linux-gnu/libumfpack.so;/usr/lib/x86_64-linux-gnu/libcholmod.so;/usr/lib/x86_64-linux-gnu/libamd.so;/usr/lib/x86_64-linux-gnu/libcamd.so;/usr/lib/x86_64-linux-gnu/libcolamd.so;/usr/lib/x86_64-linux-gnu/libccolamd.so;/usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so;/usr/lib/x86_64-linux-gnu/libsuperlu.so;/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libgomp.so;/usr/lib/x86_64-linux-gnu/libgmp.so;/usr/lib/x86_64-linux-gnu/libgmpxx.so;/usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so;-pthread;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so"
)

# Import target "dunepdelab" for configuration ""
set_property(TARGET dunepdelab APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(dunepdelab PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/lib/libdunepdelab.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
