# CMake generated Testfile for 
# Source directory: /home/paddy/pkg/dune_2d/dune-istl/dune/istl/paamg/test
# Build directory: /home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pthreadamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pthreadamgtest")
set_tests_properties(pthreadamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pthreadamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pthreadfastamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pthreadfastamgtest")
set_tests_properties(pthreadfastamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pthreadfastamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pthreadtwoleveltest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pthreadtwoleveltest")
set_tests_properties(pthreadtwoleveltest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pthreadtwoleveltest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pthreaddirectamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pthreaddirectamgtest")
set_tests_properties(pthreaddirectamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pthreaddirectamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pthreaddirectfastamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pthreaddirectfastamgtest")
set_tests_properties(pthreaddirectfastamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pthreaddirectfastamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pthreaddirecttwoleveltest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pthreaddirecttwoleveltest")
set_tests_properties(pthreaddirecttwoleveltest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pthreaddirecttwoleveltest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(amgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/amgtest")
set_tests_properties(amgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "amgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(fastamg "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/fastamg")
set_tests_properties(fastamg PROPERTIES  PROCESSORS "1" REQUIRED_FILES "fastamg" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(superluamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/superluamgtest")
set_tests_properties(superluamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "superluamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(superlufastamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/superlufastamgtest")
set_tests_properties(superlufastamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "superlufastamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(umfpackamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/umfpackamgtest")
set_tests_properties(umfpackamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "umfpackamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(umfpackfastamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/umfpackfastamgtest")
set_tests_properties(umfpackfastamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "umfpackfastamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(twolevelmethodtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/twolevelmethodtest")
set_tests_properties(twolevelmethodtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "twolevelmethodtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(graphtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/graphtest")
set_tests_properties(graphtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "graphtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(kamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/kamgtest")
set_tests_properties(kamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "kamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(transfertest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/transfertest")
set_tests_properties(transfertest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "transfertest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(twolevelmethodschwarztest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/twolevelmethodschwarztest")
set_tests_properties(twolevelmethodschwarztest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "twolevelmethodschwarztest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(galerkintest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/galerkintest")
set_tests_properties(galerkintest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "galerkintest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(hierarchytest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/hierarchytest")
set_tests_properties(hierarchytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "hierarchytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pamgtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pamgtest")
set_tests_properties(pamgtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pamgtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pamg_comm_repart_test "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/paamg/test/pamg_comm_repart_test")
set_tests_properties(pamg_comm_repart_test PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pamg_comm_repart_test" SKIP_RETURN_CODE "77" TIMEOUT "300")
