set(prefix /usr/local)
set(exec_prefix ${prefix})
set(libdir ${exec_prefix}/lib)
set(includedir ${prefix}/include)
set(UG_PARALLEL yes)
set(UG_FOR_DUNE yes)
set(UG_LIBRARIES -ldevS)
set(UG_LIBRARY_FLAGS -L${libdir})
set(UG_INCLUDES ${includedir})
set(UG_COMPILE_FLAGS -DUG_USE_SYSTEM_HEAP=1 -DUGLIB -DModelP)
