# CMake generated Testfile for 
# Source directory: /home/paddy/pkg/dune_2d/pdelab_interface/dune/pdelab/test/fem
# Build directory: /home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testrt0simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt0simplex2dfem")
set_tests_properties(testrt0simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt0simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt1simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt1simplex2dfem")
set_tests_properties(testrt1simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt1simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt0cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt0cube2dfem")
set_tests_properties(testrt0cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt0cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt1cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt1cube2dfem")
set_tests_properties(testrt1cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt1cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt2cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt2cube2dfem")
set_tests_properties(testrt2cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt2cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt0cube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt0cube3dfem")
set_tests_properties(testrt0cube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt0cube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrt1cube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrt1cube3dfem")
set_tests_properties(testrt1cube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrt1cube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testbdm1simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testbdm1simplex2dfem")
set_tests_properties(testbdm1simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testbdm1simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testbdm1cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testbdm1cube2dfem")
set_tests_properties(testbdm1cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testbdm1cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb0simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb0simplex2dfem")
set_tests_properties(testopb0simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb0simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb1simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb1simplex2dfem")
set_tests_properties(testopb1simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb1simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb2simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb2simplex2dfem")
set_tests_properties(testopb2simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb2simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb3simplex2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb3simplex2dfem")
set_tests_properties(testopb3simplex2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb3simplex2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb0cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb0cube2dfem")
set_tests_properties(testopb0cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb0cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb1cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb1cube2dfem")
set_tests_properties(testopb1cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb1cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb2cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb2cube2dfem")
set_tests_properties(testopb2cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb2cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb3cube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb3cube2dfem")
set_tests_properties(testopb3cube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb3cube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb0simplex3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb0simplex3dfem")
set_tests_properties(testopb0simplex3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb0simplex3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb1simplex3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb1simplex3dfem")
set_tests_properties(testopb1simplex3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb1simplex3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb2simplex3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb2simplex3dfem")
set_tests_properties(testopb2simplex3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb2simplex3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb3simplex3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb3simplex3dfem")
set_tests_properties(testopb3simplex3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb3simplex3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb0cube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb0cube3dfem")
set_tests_properties(testopb0cube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb0cube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb1cube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb1cube3dfem")
set_tests_properties(testopb1cube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb1cube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb2cube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb2cube3dfem")
set_tests_properties(testopb2cube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb2cube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testopb3cube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testopb3cube3dfem")
set_tests_properties(testopb3cube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testopb3cube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp02dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp02dfem")
set_tests_properties(testp02dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp02dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp12dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp12dfem")
set_tests_properties(testp12dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp12dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp22dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp22dfem")
set_tests_properties(testp22dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp22dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp32dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp32dfem")
set_tests_properties(testp32dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp32dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp03dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp03dfem")
set_tests_properties(testp03dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp03dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp13dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp13dfem")
set_tests_properties(testp13dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp13dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp23dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp23dfem")
set_tests_properties(testp23dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp23dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testp33dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testp33dfem")
set_tests_properties(testp33dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testp33dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrannacherturekcube2dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrannacherturekcube2dfem")
set_tests_properties(testrannacherturekcube2dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrannacherturekcube2dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testrannacherturekcube3dfem "/home/paddy/pkg/dune_2d/pdelab_interface/build-cmake/dune/pdelab/test/fem/testrannacherturekcube3dfem")
set_tests_properties(testrannacherturekcube3dfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testrannacherturekcube3dfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
