# CMake generated Testfile for 
# Source directory: /home/paddy/pkg/dune_2d/dune-istl/dune/istl/test
# Build directory: /home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(basearraytest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/basearraytest")
set_tests_properties(basearraytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "basearraytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bcrsassigntest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/bcrsassigntest")
set_tests_properties(bcrsassigntest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bcrsassigntest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bcrsnormtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/bcrsnormtest")
set_tests_properties(bcrsnormtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bcrsnormtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(dotproducttest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/dotproducttest")
set_tests_properties(dotproducttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "dotproducttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(complexmatrixtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/complexmatrixtest")
set_tests_properties(complexmatrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "complexmatrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(fieldvectortest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/fieldvectortest")
set_tests_properties(fieldvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "fieldvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(matrixnormtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/matrixnormtest")
set_tests_properties(matrixnormtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "matrixnormtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(matrixutilstest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/matrixutilstest")
set_tests_properties(matrixutilstest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "matrixutilstest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(matrixtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/matrixtest")
set_tests_properties(matrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "matrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bvectortest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/bvectortest")
set_tests_properties(bvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(vbvectortest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/vbvectortest")
set_tests_properties(vbvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "vbvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bcrsbuild "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/bcrsbuild")
set_tests_properties(bcrsbuild PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bcrsbuild" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bcrsimplicitbuild "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/bcrsimplicitbuild")
set_tests_properties(bcrsimplicitbuild PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bcrsimplicitbuild" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(matrixiteratortest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/matrixiteratortest")
set_tests_properties(matrixiteratortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "matrixiteratortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mmtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/mmtest")
set_tests_properties(mmtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "mmtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(multitypeblockmatrixtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/multitypeblockmatrixtest")
set_tests_properties(multitypeblockmatrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "multitypeblockmatrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(multitypeblockvectortest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/multitypeblockvectortest")
set_tests_properties(multitypeblockvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "multitypeblockvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mv "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/mv")
set_tests_properties(mv PROPERTIES  PROCESSORS "1" REQUIRED_FILES "mv" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(iotest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/iotest")
set_tests_properties(iotest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "iotest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(inverseoperator2prectest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/inverseoperator2prectest")
set_tests_properties(inverseoperator2prectest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "inverseoperator2prectest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(scaledidmatrixtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/scaledidmatrixtest")
set_tests_properties(scaledidmatrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "scaledidmatrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(solvertest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/solvertest")
set_tests_properties(solvertest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "solvertest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(solveraborttest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/solveraborttest")
set_tests_properties(solveraborttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "solveraborttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test_pardiso "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/test_pardiso")
set_tests_properties(test_pardiso PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test_pardiso" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(superlustest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/superlustest")
set_tests_properties(superlustest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "superlustest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(superlutest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/superlutest")
set_tests_properties(superlutest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "superlutest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(superluctest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/superluctest")
set_tests_properties(superluctest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "superluctest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(superluztest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/superluztest")
set_tests_properties(superluztest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "superluztest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(complexrhstest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/complexrhstest")
set_tests_properties(complexrhstest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "complexrhstest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(umfpacktest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/umfpacktest")
set_tests_properties(umfpacktest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "umfpacktest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(ldltest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/ldltest")
set_tests_properties(ldltest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "ldltest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(spqrtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/spqrtest")
set_tests_properties(spqrtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "spqrtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(overlappingschwarztest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/overlappingschwarztest")
set_tests_properties(overlappingschwarztest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "overlappingschwarztest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(matrixredisttest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/matrixredisttest")
set_tests_properties(matrixredisttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "matrixredisttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(vectorcommtest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/vectorcommtest")
set_tests_properties(vectorcommtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "vectorcommtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(matrixmarkettest "/home/paddy/pkg/dune_2d/dune-istl/build-cmake/dune/istl/test/matrixmarkettest")
set_tests_properties(matrixmarkettest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "matrixmarkettest" SKIP_RETURN_CODE "77" TIMEOUT "300")
