# CMake generated Testfile for 
# Source directory: /home/paddy/pkg/dune_2d/dune-localfunctions/dune/localfunctions/test
# Build directory: /home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(brezzidouglasmarinielementtest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/brezzidouglasmarinielementtest")
set_tests_properties(brezzidouglasmarinielementtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "brezzidouglasmarinielementtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(dualmortarelementtest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/dualmortarelementtest")
set_tests_properties(dualmortarelementtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "dualmortarelementtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(hierarchicalelementtest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/hierarchicalelementtest")
set_tests_properties(hierarchicalelementtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "hierarchicalelementtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testgenericfem "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/testgenericfem")
set_tests_properties(testgenericfem PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testgenericfem" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(lagrangeshapefunctiontest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/lagrangeshapefunctiontest")
set_tests_properties(lagrangeshapefunctiontest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "lagrangeshapefunctiontest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(monomialshapefunctiontest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/monomialshapefunctiontest")
set_tests_properties(monomialshapefunctiontest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "monomialshapefunctiontest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(rannacherturekelementtest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/rannacherturekelementtest")
set_tests_properties(rannacherturekelementtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "rannacherturekelementtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(raviartthomaselementtest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/raviartthomaselementtest")
set_tests_properties(raviartthomaselementtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "raviartthomaselementtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(refinedelementtest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/refinedelementtest")
set_tests_properties(refinedelementtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "refinedelementtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(virtualshapefunctiontest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/virtualshapefunctiontest")
set_tests_properties(virtualshapefunctiontest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "virtualshapefunctiontest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-edges0 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-edges0")
set_tests_properties(test-edges0 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-edges0" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-finiteelementcache "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-finiteelementcache")
set_tests_properties(test-finiteelementcache PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-finiteelementcache" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(globalmonomialfunctionstest "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/globalmonomialfunctionstest")
set_tests_properties(globalmonomialfunctionstest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "globalmonomialfunctionstest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-pk2d "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-pk2d")
set_tests_properties(test-pk2d PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-pk2d" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-power-monomial "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-power-monomial")
set_tests_properties(test-power-monomial PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-power-monomial" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-q1 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-q1")
set_tests_properties(test-q1 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-q1" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-q2 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-q2")
set_tests_properties(test-q2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-q2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-lagrange1 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-lagrange1")
set_tests_properties(test-lagrange1 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-lagrange1" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-lagrange2 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-lagrange2")
set_tests_properties(test-lagrange2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-lagrange2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-lagrange3 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-lagrange3")
set_tests_properties(test-lagrange3 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-lagrange3" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-lagrange4 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-lagrange4")
set_tests_properties(test-lagrange4 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-lagrange4" SKIP_RETURN_CODE "77" TIMEOUT "600")
add_test(test-orthonormal1 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-orthonormal1")
set_tests_properties(test-orthonormal1 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-orthonormal1" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-orthonormal2 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-orthonormal2")
set_tests_properties(test-orthonormal2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-orthonormal2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-orthonormal3 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-orthonormal3")
set_tests_properties(test-orthonormal3 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-orthonormal3" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-orthonormal4 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-orthonormal4")
set_tests_properties(test-orthonormal4 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-orthonormal4" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-raviartthomassimplex1 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-raviartthomassimplex1")
set_tests_properties(test-raviartthomassimplex1 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-raviartthomassimplex1" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-raviartthomassimplex2 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-raviartthomassimplex2")
set_tests_properties(test-raviartthomassimplex2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-raviartthomassimplex2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-raviartthomassimplex3 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-raviartthomassimplex3")
set_tests_properties(test-raviartthomassimplex3 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-raviartthomassimplex3" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(test-raviartthomassimplex4 "/home/paddy/pkg/dune_2d/dune-localfunctions/build-cmake/dune/localfunctions/test/test-raviartthomassimplex4")
set_tests_properties(test-raviartthomassimplex4 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "test-raviartthomassimplex4" SKIP_RETURN_CODE "77" TIMEOUT "300")
