# CMake generated Testfile for 
# Source directory: /home/paddy/pkg/dune_2d/dune-common/dune/common/test
# Build directory: /home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(arithmetictestsuitetest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/arithmetictestsuitetest")
set_tests_properties(arithmetictestsuitetest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "arithmetictestsuitetest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(arraylisttest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/arraylisttest")
set_tests_properties(arraylisttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "arraylisttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(arraydeprecationtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/arraydeprecationtest")
set_tests_properties(arraydeprecationtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "arraydeprecationtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(arraytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/arraytest")
set_tests_properties(arraytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "arraytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(assertandreturntest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/assertandreturntest")
set_tests_properties(assertandreturntest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "assertandreturntest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(assertandreturntest_compiletime_fail "/usr/bin/cmake" "--build" "." "--target" "assertandreturntest_compiletime_fail" "--config" "")
set_tests_properties(assertandreturntest_compiletime_fail PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(assertandreturntest_ndebug "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/assertandreturntest_ndebug")
set_tests_properties(assertandreturntest_ndebug PROPERTIES  PROCESSORS "1" REQUIRED_FILES "assertandreturntest_ndebug" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(autocopytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/autocopytest")
set_tests_properties(autocopytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "autocopytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bigunsignedinttest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/bigunsignedinttest")
set_tests_properties(bigunsignedinttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bigunsignedinttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(bitsetvectortest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/bitsetvectortest")
set_tests_properties(bitsetvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "bitsetvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(boundscheckingtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/boundscheckingtest")
set_tests_properties(boundscheckingtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "boundscheckingtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(boundscheckingmvtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/boundscheckingmvtest")
set_tests_properties(boundscheckingmvtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "boundscheckingmvtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(boundscheckingoptest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/boundscheckingoptest")
set_tests_properties(boundscheckingoptest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "boundscheckingoptest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(calloncetest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/calloncetest")
set_tests_properties(calloncetest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "calloncetest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(check_fvector_size "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/check_fvector_size")
set_tests_properties(check_fvector_size PROPERTIES  PROCESSORS "1" REQUIRED_FILES "check_fvector_size" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(check_fvector_size_fail1 "/usr/bin/cmake" "--build" "." "--target" "check_fvector_size_fail1" "--config" "")
set_tests_properties(check_fvector_size_fail1 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(check_fvector_size_fail2 "/usr/bin/cmake" "--build" "." "--target" "check_fvector_size_fail2" "--config" "")
set_tests_properties(check_fvector_size_fail2 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(classnametest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/classnametest")
set_tests_properties(classnametest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "classnametest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(concept "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/concept")
set_tests_properties(concept PROPERTIES  PROCESSORS "1" REQUIRED_FILES "concept" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(debugaligntest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/debugaligntest")
set_tests_properties(debugaligntest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "debugaligntest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(densematrixassignmenttest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/densematrixassignmenttest")
set_tests_properties(densematrixassignmenttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "densematrixassignmenttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(densematrixassignmenttest_fail0 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail0" "--config" "")
set_tests_properties(densematrixassignmenttest_fail0 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(densematrixassignmenttest_fail1 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail1" "--config" "")
set_tests_properties(densematrixassignmenttest_fail1 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(densematrixassignmenttest_fail2 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail2" "--config" "")
set_tests_properties(densematrixassignmenttest_fail2 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(densematrixassignmenttest_fail3 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail3" "--config" "")
set_tests_properties(densematrixassignmenttest_fail3 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(densematrixassignmenttest_fail4 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail4" "--config" "")
set_tests_properties(densematrixassignmenttest_fail4 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(densematrixassignmenttest_fail5 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail5" "--config" "")
set_tests_properties(densematrixassignmenttest_fail5 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(densematrixassignmenttest_fail6 "/usr/bin/cmake" "--build" "." "--target" "densematrixassignmenttest_fail6" "--config" "")
set_tests_properties(densematrixassignmenttest_fail6 PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(diagonalmatrixtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/diagonalmatrixtest")
set_tests_properties(diagonalmatrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "diagonalmatrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(dynmatrixtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/dynmatrixtest")
set_tests_properties(dynmatrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "dynmatrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(dynvectortest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/dynvectortest")
set_tests_properties(dynvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "dynvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(densevectortest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/densevectortest")
set_tests_properties(densevectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "densevectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(enumsettest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/enumsettest")
set_tests_properties(enumsettest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "enumsettest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(filledarraytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/filledarraytest")
set_tests_properties(filledarraytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "filledarraytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(fmatrixtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/fmatrixtest")
set_tests_properties(fmatrixtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "fmatrixtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(functiontest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/functiontest")
set_tests_properties(functiontest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "functiontest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(fvectortest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/fvectortest")
set_tests_properties(fvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "fvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(genericiterator_compile_fail "/usr/bin/cmake" "--build" "." "--target" "genericiterator_compile_fail" "--config" "")
set_tests_properties(genericiterator_compile_fail PROPERTIES  PROCESSORS "1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(gcdlcmtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/gcdlcmtest")
set_tests_properties(gcdlcmtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "gcdlcmtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(hybridutilitiestest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/hybridutilitiestest")
set_tests_properties(hybridutilitiestest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "hybridutilitiestest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(indicestest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/indicestest")
set_tests_properties(indicestest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "indicestest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(integersequence "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/integersequence")
set_tests_properties(integersequence PROPERTIES  PROCESSORS "1" REQUIRED_FILES "integersequence" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(iteratorfacadetest2 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/iteratorfacadetest2")
set_tests_properties(iteratorfacadetest2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "iteratorfacadetest2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(iteratorfacadetest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/iteratorfacadetest")
set_tests_properties(iteratorfacadetest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "iteratorfacadetest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(lrutest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/lrutest")
set_tests_properties(lrutest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "lrutest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpicollectivecommunication "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpicollectivecommunication")
set_tests_properties(mpicollectivecommunication PROPERTIES  PROCESSORS "1" REQUIRED_FILES "mpicollectivecommunication" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpicollectivecommunication-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpicollectivecommunication")
set_tests_properties(mpicollectivecommunication-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "mpicollectivecommunication" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpiguardtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpiguardtest")
set_tests_properties(mpiguardtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "mpiguardtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpiguardtest-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpiguardtest")
set_tests_properties(mpiguardtest-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "mpiguardtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpihelpertest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpihelpertest")
set_tests_properties(mpihelpertest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "mpihelpertest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpihelpertest-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpihelpertest")
set_tests_properties(mpihelpertest-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "mpihelpertest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpihelpertest2 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpihelpertest2")
set_tests_properties(mpihelpertest2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "mpihelpertest2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(mpihelpertest2-mpi-2 "/usr/local/bin/mpiexec" "-n" "2" "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/mpihelpertest2")
set_tests_properties(mpihelpertest2-mpi-2 PROPERTIES  PROCESSORS "2" REQUIRED_FILES "mpihelpertest2" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(overloadsettest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/overloadsettest")
set_tests_properties(overloadsettest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "overloadsettest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(parameterizedobjecttest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/parameterizedobjecttest")
set_tests_properties(parameterizedobjecttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "parameterizedobjecttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(parametertreelocaletest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/parametertreelocaletest")
set_tests_properties(parametertreelocaletest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "parametertreelocaletest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(parametertreetest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/parametertreetest")
set_tests_properties(parametertreetest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "parametertreetest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(pathtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/pathtest")
set_tests_properties(pathtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "pathtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(poolallocatortest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/poolallocatortest")
set_tests_properties(poolallocatortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "poolallocatortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(rangeutilitiestest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/rangeutilitiestest")
set_tests_properties(rangeutilitiestest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "rangeutilitiestest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(reservedvectortest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/reservedvectortest")
set_tests_properties(reservedvectortest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "reservedvectortest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(shared_ptrtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/shared_ptrtest")
set_tests_properties(shared_ptrtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "shared_ptrtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(singletontest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/singletontest")
set_tests_properties(singletontest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "singletontest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(sllisttest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/sllisttest")
set_tests_properties(sllisttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "sllisttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(stdapplytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/stdapplytest")
set_tests_properties(stdapplytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "stdapplytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(stdtypetraitstest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/stdtypetraitstest")
set_tests_properties(stdtypetraitstest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "stdtypetraitstest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(streamoperatorstest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/streamoperatorstest")
set_tests_properties(streamoperatorstest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "streamoperatorstest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(streamtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/streamtest")
set_tests_properties(streamtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "streamtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(stringutilitytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/stringutilitytest")
set_tests_properties(stringutilitytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "stringutilitytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testdebugallocator "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testdebugallocator")
set_tests_properties(testdebugallocator PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdebugallocator" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(testdebugallocator_fail1 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testdebugallocator_fail1")
set_tests_properties(testdebugallocator_fail1 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdebugallocator_fail1" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(testdebugallocator_fail2 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testdebugallocator_fail2")
set_tests_properties(testdebugallocator_fail2 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdebugallocator_fail2" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(testdebugallocator_fail3 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testdebugallocator_fail3")
set_tests_properties(testdebugallocator_fail3 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdebugallocator_fail3" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(testdebugallocator_fail4 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testdebugallocator_fail4")
set_tests_properties(testdebugallocator_fail4 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdebugallocator_fail4" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(testdebugallocator_fail5 "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testdebugallocator_fail5")
set_tests_properties(testdebugallocator_fail5 PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testdebugallocator_fail5" SKIP_RETURN_CODE "77" TIMEOUT "300" WILL_FAIL "true")
add_test(testfloatcmp "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/testfloatcmp")
set_tests_properties(testfloatcmp PROPERTIES  PROCESSORS "1" REQUIRED_FILES "testfloatcmp" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(to_unique_ptrtest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/to_unique_ptrtest")
set_tests_properties(to_unique_ptrtest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "to_unique_ptrtest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(tupleutilitytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/tupleutilitytest")
set_tests_properties(tupleutilitytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "tupleutilitytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(typeutilitytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/typeutilitytest")
set_tests_properties(typeutilitytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "typeutilitytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(typelisttest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/typelisttest")
set_tests_properties(typelisttest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "typelisttest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(utilitytest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/utilitytest")
set_tests_properties(utilitytest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "utilitytest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(eigenvaluestest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/eigenvaluestest")
set_tests_properties(eigenvaluestest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "eigenvaluestest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(optionaltest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/optionaltest")
set_tests_properties(optionaltest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "optionaltest" SKIP_RETURN_CODE "77" TIMEOUT "300")
add_test(versiontest "/home/paddy/pkg/dune_2d/dune-common/build-cmake/dune/common/test/versiontest")
set_tests_properties(versiontest PROPERTIES  PROCESSORS "1" REQUIRED_FILES "versiontest" SKIP_RETURN_CODE "77" TIMEOUT "300")
